server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: sda-eureka #Eureka服务端的实例名称 #localhost
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:
      defaultZone: http://localhost:7001/eureka/
