server:
  port: 9002

spring:
  application:
    name: chaoxing-web
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#info配置
info:
  app.name: ChaoxingWeb
  company.name: www.zxja.com


#开启hystrix降级
#feign:
#  hystrix:
#    enabled: true
