server:
  port: 9001

spring:
  application:
    name: Bili-web
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#info配置
info:
  app.name: BiliWeb
  company.name: www.zxja.com


#开启hystrix降级
feign:
  hystrix:
    enabled: true
