server:
  port: 8002

#mybatis配置
mybatis:
  type-aliases-package: com.tfjy.sda.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring的配置
spring:
  application:
    name: chaoxing-Service
  datasource:
    type:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://d-mysql.dmsd.tech:3306/sda_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: sda
    password: sda

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#  instance:
#    instance-id: BiliService # 修改eureka上的默认描述信息！
xxl:
  job:
    admin:
      addresses: http://d-xxljob.tfjybj.cn/job-admin-dev
    executor:
      appname: sda-chaoxing-job
      ip:
      port: 9998
      logpath: /data/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

#info配置
info:
  app.name: ChaoxingService
  company.name: www.zxja.com
#权限登录接口
jurisdiction:
  loginUrl: http://192.168.60.109:8081/auth-web/access/login

#积分加分接口
integral:
  addUrl: http://d-point.dmsd.tech:8118/integral-web/addIntegralController/addIntegralDetail
