server:
  port: 9003

spring:
  application:
    name: LAP-web
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#info配置
info:
  app.name: LAPWeb
  company.name: www.zxja.com


#开启hystrix降级
#feign:
#  hystrix:
#    enabled: true
