server:
  port: 9002

spring:
  application:
    name: chaoxing-web
  main:
    allow-bean-definition-overriding: true
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

#info配置
info:
  app.name: ChaoxingWeb
  company.name: www.zxja.com


#开启hystrix降级
feign:
  hystrix:
    enabled: true

logging:
  level:
    #feign日志以哪个级别监控哪个接口
    com.tfjy.sda.service.TopicFeignService: debug
